version: '3.7'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"     # MinIO server
      - "9001:9001"     # MinIO console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
